### ISSUE TITLE
Home page hover text

### ISSUE THREAD

**Issue by richardltyler** [gaj23/rancid#6]
# Story 
As a user, I want to hover over a movie's poster and see the title displayed without overlapping the movie below/next to it.

## Acceptance Criteria
When we check all the movie tiles in desktop mode, all title remain readable when hovered over. 

### Concerns 
- [x] how much time should we spend on this?

**Comment by gaj23** [comment]
For now, the experience is fine. Not stellar, but whatever.

**Comment by gaj23** [comment]
This is something that a user in desktop mode would experience. Not mobile.
